name: Build

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: build-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 45

        steps:
            -   uses: actions/checkout@v4

            -   name: Validate Gradle Wrapper
                uses: gradle/actions/wrapper-validation@v4

            -   name: set up JDK
                uses: actions/setup-java@v5
                with:
                    distribution: 'zulu'
                    java-version: 21

            -   uses: gradle/actions/setup-gradle@v4
                with:
                    gradle-home-cache-cleanup: true

            -   name: Check spotless
                run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

            -   name: Check lint
                run: ./gradlew lintDebug

            -   name: Build
                run: ./gradlew assembleDebug

            -   name: Run tests
                run: ./gradlew test

            -   name: Run check
                run: ./gradlew check
